<?php

namespace Database\Seeders;

use App\Models\Order;
use App\Models\OrderStatus;
use App\Models\Product;
use App\Models\Role;
use App\Models\User;
use App\Models\Wilaya;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Seed the orders table with random student orders.
     */
    public function run(): void
    {
        $studentRole = Role::where('code', 'student')->first();
        if (!$studentRole) {
            $this->command->error("Student role not found. Please run RoleSeeder first.");
            return;
        }

        $students = User::where('role_id', $studentRole->id)->get();
        $products = Product::all();
        $wilayas = Wilaya::all();
        $statuses = OrderStatus::all();

        if ($students->isEmpty() || $products->isEmpty() || $wilayas->isEmpty() || $statuses->isEmpty()) {
            $this->command->error("Missing required data (students, products, wilayas, or statuses). Please run other seeders first.");
            return;
        }

        $addresses = [
            'Cité Universitaire, Bâtiment C, Chambre 204',
            'Résidence 1000 Logements, Bloc 12, Appt 3',
            'Rue Didouche Mourad, N° 45',
            'Boulevard de l\'ALN, Immeuble Bellevue, 3ème étage',
            'Cité des 500 Logements, Entrée B',
            'Hai El Badr, Bâtiment 7, Appt 16',
            'Campus Universitaire, Pavillon Sciences',
            'Lotissement les Oliviers, Villa N° 22',
        ];

        // Create 12 random orders
        foreach (range(1, 12) as $i) {
            $student        = $students->random();
            $wilaya         = $wilayas->random();
            $orderProducts  = $products->random(rand(1, 4));
            $totalPrice     = 0;

            $order = Order::create([
                'user_id'          => $student->id,
                // code is auto-generated by Order::boot()
                'total_price'      => 0, // will be updated below
                'shipping_address' => $addresses[array_rand($addresses)] . ', ' . $wilaya->name,
                'wilaya_id'        => $wilaya->id,
                'order_status_id'  => $statuses->random()->id,
            ]);

            // Attach products to the order
            foreach ($orderProducts as $product) {
                $qty      = rand(1, 5);
                $snapshot = $product->price;
                $totalPrice += $snapshot * $qty;

                $order->products()->attach($product->id, [
                    'quantity' => $qty,
                    'price'    => $snapshot,
                ]);
            }

            // Update order total
            $order->update(['total_price' => $totalPrice]);
        }
    }
}
